### ISSUE TITLE
Generate and test category model

### ISSUE THREAD

**Issue by 0smose** [OnyJ/PetitBacAPI#4]
**Why ?**
Need to create and manipulate different categories

**How**
- [x]  Task 1 rails g model Category name:string

- [x]  Task 2 add relation to model
has_many :join_category_games
has_many :games, through: :join_category_games

**Must Have**
 A functionnal Category model

**Reading List**
https://www.thehackingproject.org/dashboard/courses/1/weeks/4/days/4?locale=fr

**Comment by AugustinBoju** [comment]
done
